# Generated by Django 4.2.4 on 2023-09-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=123, max_length=256),
            preserve_default=False,
        ),
    ]
