# Generated by Django 4.2.4 on 2023-09-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
