# Generated by Django 4.2.4 on 2023-09-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_user_label1_user_label2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='label1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='label2',
        ),
    ]
